import type { AdminPromoType, ItemType } from "./types";

/**
 * Interfaces for database tables:
 * - public.store
 * - public.promo
 * - public.promo_store
 *
 * Request interfaces represent payloads used to create/update rows (omit generated PKs).
 * Response interfaces represent full rows returned from the database.
 */

// User-defined / unknown enum from DB — keep as string for now, can be tightened later.

/* ---------------------- public.store ---------------------- */
/** Full row returned from `public.store` */
export interface StoreResponse {
   id: number; // GENERATED ALWAYS AS IDENTITY
   name: string;
   company: string;
   address: string;
   // `route` is nullable in the schema (no NOT NULL constraint)
   route: string;
   type: string;
}

/** Payload to create or update a `public.store` row. `id` is generated by DB. */
export interface StoreRequest {
   name: string;
   company: string;
   address: string;
   route: string;
   type: string;
}

/* ---------------------- public.promo ---------------------- */
/** Full row returned from `public.promo` */
export interface PromoResponse {
   id_promo: number; // identity primary key
   title_promo: string;
   min_transaction_promo: number;
   tenor_promo: number;
   subsidi_promo: number; // numeric in DB — use number (may be decimal)
   admin_promo: number; // numeric
   admin_promo_type: AdminPromoType;
   interest_rate: number; // numeric
   voucher_code: string;
   is_active: boolean;
   start_date_promo: string; // ISO date string (YYYY-MM-DD)
   end_date_promo: string; // ISO date string
   free_installment: number;
}

/** Payload to create a `public.promo` row. DB will generate `id_promo`. */
export interface PromoRequest {
   title_promo: string;
   min_transaction_promo: number;
   tenor_promo: number;
   subsidi_promo?: number;
   admin_promo: number;
   admin_promo_type: AdminPromoType;
   interest_rate: number;
   voucher_code: string;
   start_date_promo: string | Date; // Accept either `Date` or ISO string for convenience when creating/updating
   end_date_promo: string | Date;
   free_installment?: number;
   is_active?: boolean;
}

/* ---------------------- public.promo_store ---------------------- */
/** Full row returned from `public.promo_store` */
export interface PromoStoreResponse {
   id: number; // primary key
   promo_id: number; // FK -> promo.id_promo
   store_id: number; // FK -> store.id
}

/** Payload to create a `public.promo_store` row. `id` is generated by DB. */
export interface PromoStoreRequest {
   promo_id: number;
   store_id: number;
}

/* ---------------------- Object Data ---------------------- */
export interface PromoObject {
   title_promo: string;
   min_transaction_promo: number;
   tenor_promo: number;
   subsidi_promo: number;
   admin_promo: number;
   admin_promo_type: AdminPromoType;
   interest_rate: number;
   voucher_code: string;
   is_active: boolean;
   start_date_promo: string;
   end_date_promo: string;
   free_installment: number;
}

export interface StoreObject {
   name: string;
   company: string;
   address: string;
   route: string;
}
/* ---------------------- Item Store & Promo Props Component Data ---------------------- */
export interface ItemStoreProps {
   data: StoreObject;
   buttons: { label: string; onclick: () => void }[];
}
export interface ItemPromoProps {
   data: PromoObject;
   dataStores?: string[];
   buttons: { label: string; onclick: (voucher_code: string) => void }[];
}

export interface CRUDComponentProps {
   data: ItemType;
}
